webtalk_init -webtalk_dir C:/Users/gp1998/Documents/nuts/cpu/cpu_final/cpu_final.sim/sim_1/behav/xsim/xsim.dir/cpu_test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jun 25 02:32:50 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1702b7f7-1eb1-4226-87bf-a2d09068fa2b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1b15c23794114ed2b33c7b75585c5ea4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "36" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "40023040 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "641.27_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "19324_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2299916628 -regid "" -xml C:/Users/gp1998/Documents/nuts/cpu/cpu_final/cpu_final.sim/sim_1/behav/xsim/xsim.dir/cpu_test_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/gp1998/Documents/nuts/cpu/cpu_final/cpu_final.sim/sim_1/behav/xsim/xsim.dir/cpu_test_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/gp1998/Documents/nuts/cpu/cpu_final/cpu_final.sim/sim_1/behav/xsim/xsim.dir/cpu_test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
